language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements-dev.txt"
# command to run tests
notifications:
  slack: msucompsci:AuVt8PyAyo1MT00Ksk7rDhzA
script:
 - nosetests --with-coverage tests
 - flake8 .
 - codecov
